language: dart
dart:
  - "2.0.0"
before_script:
  - "pub global activate webdev"
script:
  - "webdev build --no-release -o ./build"
deploy:
  provider: firebase
  token: $FB_TOKEN
  local-dir: build/web
  on:
    branch: master
