language: dart
dart:
  - "2.0.0"
before_script:
  - "pub global activate webdev"
script:
  - "webdev build --no-release -o build"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: build/web
  on:
    branch: master
